/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertit;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDecimal = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        txtSVA = new javax.swing.JLabel();
        txtCR = new javax.swing.JLabel();
        txtFlP = new javax.swing.JLabel();
        txtCV = new javax.swing.JLabel();
        txtFP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Your Number(decimal):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Fixed Point:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Binary (S+VA):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Binary (CR):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Binary (CV):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setText("IEEE 754 Floating Point:");

        txtDecimal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtDecimal.setText("0");
        txtDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDecimalActionPerformed(evt);
            }
        });

        btnShow.setText("Show Result");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        txtSVA.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtSVA.setText("NaN");

        txtCR.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtCR.setText("NaN");

        txtFlP.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtFlP.setText("NaN");

        txtCV.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtCV.setText("NaN");

        txtFP.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtFP.setText("NaN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFlP, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSVA))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCR))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCV)
                    .addComponent(jLabel5))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFlP))
                .addGap(4, 4, 4)
                .addComponent(btnShow)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void reset() {
        txtCR.setText("NaN");
        txtCV.setText("NaN");
        txtFP.setText("NaN");
        txtFlP.setText("NaN");
        txtSVA.setText("NaN");
    }

    void error(String e) {
        JOptionPane.showMessageDialog(null, e, "ERR", 0);
    }

    static String fixedpoint(double n, int x) {
        StringBuilder sb = new StringBuilder();
        double r = n % 1;
        double l = n - r;
        sb.append(String.valueOf(toSysX((int) l, x)) + ".");
        Map<Double, Integer> map = new HashMap<>();
        map.put(r, 1);
        while (map.get(r) != 2 && sb.length() < 24) {
            r *= x;
            double add = r - r % 1;
            sb.append(String.valueOf((int) add));
            r -= add;
            if (map.containsKey(r)) {
                map.put(r, map.get(r) + 1);
            } else {
                map.put(r, 1);
            }
        }
        if (sb.charAt(sb.length() - 1) == '0') {
            sb.deleteCharAt(sb.length() - 1);
        }
        return sb.toString();
    }

    static long getMaxBit(long n) {
        return (int) (Math.log(n) / Math.log(2)) + 1;
    }

    static long complement1(long n) {
        int ans = 0;
        int bi = toSysX(n, 2);
        int pow = 1;
        while (bi >= 1) {
            ans += ((bi % 10 + 1) % 2) * pow;
            bi /= 10;
            pow *= 10;
        }
        ans += pow;
        return ans;
    }

    static long complement2(long n) {
        return toSysX(toDecimal(complement1(n), 2) + 1, 2);
    }

    static int toSysX(long decimal, int to) {
        int ans = 0, pow = 1;
        while (decimal >= 1) {
            ans += (decimal % to) * pow;
            pow *= 10;
            decimal /= to;
        }
        return ans;
    }

    static long toDecimal(long n, int x) {
        long ans = 0, pow = 1;
        while (n >= 1) {
            ans += (n % 10) * pow;
            pow *= x;
            n /= 10;
        }
        return ans;
    }

    static long fromTo(long n, int from, int to) {
        return toSysX(toDecimal(n, from), to);
    }

    static String ExtendedLeft(int n) {
        String sn = String.valueOf(n);
        StringBuilder sb = new StringBuilder(sn);
        while (sb.length() != 8 ) {
            sb.insert(0,"0");
        } 
        return sb.toString();
    }
 

    static String floatingPoint(double d) {
        StringBuilder sb = new StringBuilder();
        sb.append(d < 0 ? "1" + " " : "0" + " ");
        String m = fixedpoint(Math.abs(d), 2);
        System.out.println(m);
        int dec = m.indexOf(".") - m.indexOf("1");
        int exp = 127 + dec;
        int expo = toSysX(exp, 2);
        String ex = ExtendedLeft(expo); 
        m = m.substring(m.indexOf("1") + 1);
        sb.append(ex + " ");
        sb.append(m);
        return sb.toString();
    }
    private void txtDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDecimalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setTitle("Convert");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_formWindowOpened

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        int inp = 0;
        double d = 0;
        String s = txtDecimal.getText();
        if (!s.contains(".")) {
            try {
                inp = Integer.parseInt(txtDecimal.getText());
                reset();
            } catch (Exception ex) {
                error("invalid input...");
                reset();
            }

            txtCR.setText(String.valueOf(complement1(Math.abs(inp))));
            txtCV.setText(String.valueOf(complement2(Math.abs(inp))));
            txtSVA.setText((inp > 0 ? "0" : "1") + String.valueOf(toSysX(Math.abs(inp), 2)));
        } else {
            reset();
            try {
                d = Double.parseDouble(txtDecimal.getText());
            } catch (Exception ex) {
                error("invalid input...");
                reset();
            }
            txtFP.setText(fixedpoint(Math.abs(d), 2));
            txtFlP.setText(floatingPoint(d));
        }
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel txtCR;
    private javax.swing.JLabel txtCV;
    private javax.swing.JTextField txtDecimal;
    private javax.swing.JLabel txtFP;
    private javax.swing.JLabel txtFlP;
    private javax.swing.JLabel txtSVA;
    // End of variables declaration//GEN-END:variables
}
